[changelog]
body = """## RinUI{% if version %} ({{ version }}){% endif %}

{% macro commit_line(commit) -%}
  - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | split(pat="\n") | first | trim | upper_first }}{% if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}{% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }})){% endif %}
{%- endmacro %}

{% for group, commits in commits | group_by(attribute="group") %}
{%- if group == "<!-- 11 -->ğŸ“ Other" %}
### {{ group }}
<details>

{% for commit in commits | unique(attribute="message") -%}
  {{ self::commit_line(commit=commit) }}
{% endfor %}

</details>
{%- else %}
### {{ group }}
{% for commit in commits | unique(attribute="message") -%}
  {{ self::commit_line(commit=commit) }}
{% endfor %}
{%- endif %}

{% endfor -%}

---

{% if version %}
    {% if previous.version %}
      ğŸ“‹ **Full Changelog**: [{{ previous.version }}...{{ version }}]({{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }})
    {% endif %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"
trim = true

[git]
commit_parsers = [
  {group = "<!-- 00 -->â›°ï¸  Features", message = "^feat"},
  {group = "<!-- 01 -->ğŸ› Bug Fixes", message = "^fix"},
  {group = "<!-- 02 -->ğŸ“š Documentation", message = "^doc"},
  {group = "<!-- 03 -->ğŸ¨ Styles", message = "^style"},
  {group = "<!-- 04 -->ğŸšœ Refactoring", message = "^refactor"},
  {group = "<!-- 05 -->âš¡ Performance Improvements", message = "^perf"},
  {group = "<!-- 06 -->ğŸ§ª Tests", message = "^test"},
  {group = "<!-- 07 -->Builds", message = "^build"},
  {group = "<!-- 09 -->âš™ï¸ Chores", message = "^chore"},
  {group = "<!-- 10 -->â—€ï¸ Reverts", message = "^revert"},
  {group = "<!-- 11 -->ğŸ“ Other", message = ".*"},
  {message = "^chore\\(release\\)", skip = true}
]
conventional_commits = true
filter_commits = false
filter_unconventional = false
link_parsers = []
protect_breaking_commits = false
sort_commits = "newest"
split_commits = false
topo_order = false
