[changelog]
body = """

{% macro commit_line(commit) -%}
  - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | split(pat="\n") | first | trim | upper_first }}{% if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}{% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }})){% endif %}
{%- endmacro %}

"""## RinUI{% if version %} ({{ version }}){% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
{%- if group == "<!-- 11 -->ğŸ“ Other" %}
### {{ group }}
<details>

{% for commit in commits | unique(attribute="message") -%}
  {{ self::commit_line(commit=commit) }}
{% endfor %}

</details>
{%- else %}
### {{ group }}
{% for commit in commits | unique(attribute="message") -%}
  {{ self::commit_line(commit=commit) }}
{% endfor %}
{%- endif %}

{% endfor -%}

---

{% if version %}
    {% if previous.version %}
      ğŸ“‹ **Full Changelog**: [{{ previous.version }}...{{ version }}]({{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }})
    {% endif %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
trim = true
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 00 -->â›°ï¸  Features" },
    { message = "^fix", group = "<!-- 01 -->ğŸ› Bug Fixes" },
    { message = "^doc", group = "<!-- 02 -->ğŸ“š Documentation" },
    { message = "^style", group = "<!-- 03 -->ğŸ¨ Styles" },
    { message = "^refactor", group = "<!-- 04 -->ğŸšœ Refactoring" },
    { message = "^perf", group = "<!-- 05 -->âš¡ Performance Improvements" },
    { message = "^test", group = "<!-- 06 -->ğŸ§ª Tests" },
    { message = "^build", group = "<!-- 07 -->Builds"},
    { message = "^chore", group = "<!-- 09 -->âš™ï¸ Chores" },
    { message = "^revert", group = "<!-- 10 -->â—€ï¸ Reverts" },
    { message = ".*", group = "<!-- 11 -->ğŸ“ Other" }
]
protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "newest"
link_parsers = []
